title: Nesrine Arfaoui # your name (or website title) here
logo: "https://media.licdn.com/dms/image/D4E03AQFO8Li3zCnsIA/profile-displayphoto-shrink_200_200/0/1681535093854?e=1686787200&v=beta&t=NKe4A8-1xbWdubfH1kOOQYJidOw5QZ4UoHNwXw-DaGw" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  An industrial engineering major turned Data Analytic enthusiaste soon to graduate from Nova Scotia's Community College, i seek an oppurtunity to build my skills as a data analyst and contribute to this ever growing field
  <br>

  <a href="https://www.linkedin.com/in/nesrine-arfaoui-06398324b/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
