title: Nesrine Arfaoui # your name (or website title) here
logo: "C:\Users\W0476715\OneDrive - Nova Scotia Community College\Desktop" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  an Industrial engineering major
  <br><br>
  Won 2022 Halifax Innovation Challenge: sponsored by RBC and IBM
  <a href="https://innovationchallenge.agendamanagers.ca/">Read more</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/patanley/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
