title: Nesrine Arfaoui # your name (or website title) here
logo: "https://media.licdn.com/dms/image/D4E03AQFO8Li3zCnsIA/profile-displayphoto-shrink_200_200/0/1681535093854?e=1686787200&v=beta&t=NKe4A8-1xbWdubfH1kOOQYJidOw5QZ4UoHNwXw-DaGw" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  An industrial engineering major turned Data Analytic enthusiaste
  <br><br>
  Won 2022 Halifax Innovation Challenge: sponsored by RBC and IBM
  <a href="https://innovationchallenge.agendamanagers.ca/">Read more</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/patanley/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
