<!DOCTYPE html>
<html>
  <head>
title: Nesrine Arfaoui # your name (or website title) here
  <head> 
<body>
  <img src="https://media.licdn.com/dms/image/D4E03AQFO8Li3zCnsIA/profile-displayphoto-shrink_800_800/0/1681535093854?e=1686787200&v=beta&t=JaxKFXrCoaUr1XGX_M-3BrYVTeDGDgdRGKMOyO4X4kM" alt="Image description">
</body>
</html>
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  an Industrial engineering major
  <br><br>
  Won 2022 Halifax Innovation Challenge: sponsored by RBC and IBM
  <a href="https://innovationchallenge.agendamanagers.ca/">Read more</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/patanley/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
